import { lazy } from 'react';
import __Layout from './Layout.jsx';

export const PAGES = {
  "Announcements": lazy(() => import('./pages/Announcements')),
  "ApplyLeave": lazy(() => import('./pages/ApplyLeave')),
  "ClassComparison": lazy(() => import('./pages/ClassComparison')),
  "AttendanceAnalytics": lazy(() => import('./pages/AttendanceAnalytics')),
  "AttendanceApproval": lazy(() => import('./pages/AttendanceApproval')),
  "AttendanceHistory": lazy(() => import('./pages/AttendanceHistory')),
  "Communication": lazy(() => import('./pages/Communication')),
  "Dashboard": lazy(() => import('./pages/Dashboard')),
  "Diary": lazy(() => import('./pages/Diary')),
  "EditAttendance": lazy(() => import('./pages/EditAttendance')),
  "EnterMarks": lazy(() => import('./pages/EnterMarks')),
  "ExamSchedule": lazy(() => import('./pages/ExamSchedule')),
  "Home": lazy(() => import('./pages/Home')),
  "Homework": lazy(() => import('./pages/Homework')),
  "Login": lazy(() => import('./pages/Login')),
  "JoinSchool": lazy(() => import('./pages/JoinSchool')),
  "JoinTeacher": lazy(() => import('./pages/JoinTeacher')),
  "ManageClasses": lazy(() => import('./pages/ManageClasses')),
  "ManageExams": lazy(() => import('./pages/ManageExams')),
  "ManageStudents": lazy(() => import('./pages/ManageStudents')),
  "ManageSubjects": lazy(() => import('./pages/ManageSubjects')),
  "ManageTeachers": lazy(() => import('./pages/ManageTeachers')),
  "MarkAttendance": lazy(() => import('./pages/MarkAttendance')),
  "Notifications": lazy(() => import('./pages/Notifications')),
  "ParentDashboard": lazy(() => import('./pages/ParentDashboard')),
  "ParentLogin": lazy(() => import('./pages/ParentLogin')),
  "PrincipalDashboard": lazy(() => import('./pages/PrincipalDashboard')),
  "PrincipalSettings": lazy(() => import('./pages/PrincipalSettings')),
  "PtmSchedule": lazy(() => import('./pages/PtmSchedule')),
  "SubstituteLog": lazy(() => import('./pages/SubstituteLog')),
  "Reports": lazy(() => import('./pages/Reports')),
  "Register": lazy(() => import('./pages/Register')),
  "ReportCard": lazy(() => import('./pages/ReportCard')),
  "Seed": lazy(() => import('./pages/Seed')),
  "StudentProgress": lazy(() => import('./pages/StudentProgress')),
  "ReviewLeave": lazy(() => import('./pages/ReviewLeave')),
  "RoleSelection": lazy(() => import('./pages/RoleSelection')),
  "SelectClasses": lazy(() => import('./pages/SelectClasses')),
  "SetupSchool": lazy(() => import('./pages/SetupSchool')),
  "TeacherDashboard": lazy(() => import('./pages/TeacherDashboard')),
  "TeacherManageExams": lazy(() => import('./pages/TeacherManageExams')),
  "TeacherSettings": lazy(() => import('./pages/TeacherSettings')),
  "Timetable": lazy(() => import('./pages/Timetable')),
  "UnapprovedAbsences": lazy(() => import('./pages/UnapprovedAbsences')),
  "ViewMarks": lazy(() => import('./pages/ViewMarks')),
  "ViewStudents": lazy(() => import('./pages/ViewStudents')),
};

export const pagesConfig = {
  mainPage: "Home",
  Pages: PAGES,
  Layout: __Layout,
};
